import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

const raleway = Raleway({ 
  subsets: ['latin'],
  variable: "--raleway",
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(raleway.className)
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  )
}
